version: '3.7'

services:
  currency-exchange:
    image:  dkijowski/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit:  700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  currency-conversion-service:
    image:  dominosski/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit:  700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      
  naming-server:
    image:  dkijowski/naming-server:0.0.1-SNAPSHOT
    mem_limit:  700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  api-gateway:
    image:  dominosski/api-gateway:0.0.1-SNAPSHOT
    mem_limit:  700m
    ports: 
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

networks:
  currency-network: